#!/bin/bash

python3 coin_data_clean.py data_scraped/Augustus_Aur_EA1/Augustus_Aur_EA1.csv

python3 coin_data_clean.py data_scraped/Augustus_Aur_PA1/Augustus_Aur_PA1.csv

python3 coin_data_clean.py data_scraped/Augustus_Cis_EA1/Augustus_Cis_EA1.csv

python3 coin_data_clean.py data_scraped/Augustus_Cis_PA1/Augustus_Cis_PA1.csv

python3 coin_data_clean.py data_scraped/Augustus_Den_EA1/Augustus_Den_EA1.csv
python3 coin_data_clean.py data_scraped/Augustus_Den_EA2/Augustus_Den_EA2.csv
python3 coin_data_clean.py data_scraped/Augustus_Den_EA3/Augustus_Den_EA3.csv
python3 coin_data_clean.py data_scraped/Augustus_Den_EA4/Augustus_Den_EA4.csv

python3 coin_data_clean.py data_scraped/Augustus_Den_PA1/Augustus_Den_PA1.csv
python3 coin_data_clean.py data_scraped/Augustus_Den_PA2/Augustus_Den_PA2.csv
python3 coin_data_clean.py data_scraped/Augustus_Den_PA3/Augustus_Den_PA3.csv

python3 coin_data_clean.py data_scraped/Augustus_Ses_EA1/Augustus_Ses_EA1.csv

python3 coin_data_clean.py data_scraped/Augustus_Ses_PA1/Augustus_Ses_PA1.csv